site:
  title: n00 Docs
  start_page: n00tropic-cerebrum::index.adoc
content:
  sources:
    - url: https://github.com/n00tropic/n00tropic-cerebrum.git
      branches: [docs]
      start_paths: [docs]
    - url: https://github.com/n00tropic/n00-frontiers.git
      branches: [docs]
      start_paths: [docs]
    - url: https://github.com/n00tropic/n00-cortex.git
      branches: [docs]
      start_paths: [docs]
    - url: https://github.com/n00tropic/n00t.git
      branches: [docs]
      start_paths: [docs]
    - url: https://github.com/n00tropic/n00-horizons.git
      branches: [main]
      start_paths: [docs]
    - url: https://github.com/n00tropic/n00-school.git
      branches: [main]
      start_paths: [docs]
    - url: https://github.com/n00tropic/n00plicate.git
      branches: [chore/migrate-node-24]
      start_paths: [docs]
    - url: https://github.com/n00tropic/n00tropic.git
      branches: [main]
      start_paths: [docs]
    - url: https://github.com/n00tropic/n00clear-fusion.git
      branches: [main]
      start_paths: [docs]
    - url: https://github.com/n00tropic/n00menon.git
      branches: [main]
      start_paths: [.]
ui:
  bundle:
    url: ./vendor/antora/ui-bundle.zip
antora:
  extensions:
    - "@antora/lunr-extension"
asciidoc:
  attributes:
    page-pagination: ""
    sectanchors: ""
    icons: font
    source-highlighter: highlight.js
runtime:
  fetch: true
