site:
  title: n00 Docs (CI)
  start_page: n00-cerebrum::index.adoc
content:
  sources:
    - url: https://github.com/IAmJonoBo/n00tropic-cerebrum
      branches: [main]
      start_paths: [docs]
    - url: https://github.com/IAmJonoBo/n00-frontiers
      branches: [main]
      start_paths: [docs]
    - url: https://github.com/IAmJonoBo/n00-cortex
      branches: [main]
      start_paths: [docs]
    - url: https://github.com/IAmJonoBo/n00t
      branches: [main]
      start_paths: [docs]
ui:
  bundle:
    url: ./vendor/antora/ui-bundle.zip
antora:
  extensions:
    - "@antora/lunr-extension"
asciidoc:
  attributes:
    page-pagination: ""
    sectanchors: ""
    icons: font
    source-highlighter: highlight.js
runtime:
  fetch: true
