site:
  title: n00 Docs
  start_page: n00-cerebrum::index.adoc
content:
  sources:
    - url: .
      branches: [HEAD]
      start_paths: [docs]
ui:
  bundle:
    url: ./vendor/antora/ui-bundle.zip
antora:
  extensions:
    - "@antora/lunr-extension"
asciidoc:
  attributes:
    page-pagination: ""
    sectanchors: ""
    icons: font
    source-highlighter: highlight.js
runtime:
  fetch: true
