site:
  title: n00 Docs
  start_page: n00-cerebrum::index.adoc
content:
  sources:
    - url: https://github.com/IAmJonoBo/n00-cerebrum.git
      branches: [main]
      start_paths: [docs]
    - url: https://github.com/IAmJonoBo/n00-frontiers.git
      branches: [main]
      start_paths: [docs]
    - url: https://github.com/IAmJonoBo/n00-cortex.git
      branches: [main]
      start_paths: [docs]
    - url: https://github.com/IAmJonoBo/n00-horizons.git
      branches: [main]
      start_paths: [docs]
    - url: https://github.com/IAmJonoBo/n00-school.git
      branches: [main]
      start_paths: [docs]
    - url: https://github.com/IAmJonoBo/n00t.git
      branches: [main]
      start_paths: [docs]
    - url: https://github.com/IAmJonoBo/n00plicate.git
      branches: [main]
      start_paths: [docs]
    - url: https://github.com/IAmJonoBo/n00tropic.git
      branches: [main]
      start_paths: [docs]
    - url: https://github.com/IAmJonoBo/n00clear-fusion.git
      branches: [main]
      start_paths: [docs]
ui:
  bundle:
    url: https://cdn.antora.org/ui/default
    snapshot: true
antora:
  extensions:
    - "@antora/lunr-extension"
asciidoc:
  attributes:
    page-pagination: ""
    sectanchors: ""
    icons: font
    source-highlighter: highlight.js
runtime:
  fetch: true
