apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { include "example-chart.fullname" . } }
spec:
  replicas: { { .Values.replicaCount } }
  selector:
    matchLabels:
      app.kubernetes.io/name: { { include "example-chart.name" . } }
  template:
    metadata:
      labels:
        app.kubernetes.io/name: { { include "example-chart.name" . } }
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["sh", "-c", "sleep 3600"]
